### ISSUE TITLE
Example on MIL/CLAM

### ISSUE THREAD

**Issue by Tato14** [KatherLab/HIA#2]
Hi,

Could you please share an ExperimentFile using MIL/CLAM pipeline?

Thanks

**Comment by Tato14** [comment]
@narminGhaffari still having the 
```
Init train/val/test splits... ******************************************************************
Training on 0 samples
Validating on 0 samples
Testing on 0 samples
******************************************************************
Done!

Init loss function... Done!

Init Model... Done!
MIL_fc(
  (classifier): DataParallel(
    (module): Sequential(
      (0): Linear(in_features=1024, out_features=512, bias=True)
      (1): ReLU()
      (2): Dropout(p=0.25, inplace=False)
      (3): Linear(in_features=512, out_features=2, bias=True)
    )
  )
)
Total number of parameters: 525826
Total number of trainable parameters: 525826

Init optimizer ... Done!

Init Loaders... Traceback (most recent call last):
  File "/home/jgibert/KatherLab/HIA/Main.py", line 40, in <module>
    ClamMILTraining(args)
  File "/home/jgibert/KatherLab/HIA/ClamMILTraining.py", line 137, in ClamMILTraining
    patient_results, aucList  = Train_MIL_CLAM(datasets = datasets, cur = i, args = args)
  File "/home/jgibert/KatherLab/HIA/utils/core_utils.py", line 123, in Train_MIL_CLAM
    train_loader = Get_split_loader(train_split, training = True, testing = args.testing, weighted = args.weighted_sample)
  File "/home/jgibert/KatherLab/HIA/utils/data_utils.py", line 278, in Get_split_loader
    weights = Make_weights_for_balanced_classes_split(split_dataset)
  File "/home/jgibert/KatherLab/HIA/utils/data_utils.py", line 296, in Make_weights_for_balanced_classes_split
    weight_per_class = [N/len(dataset.slide_cls_ids[c]) for c in range(len(dataset.slide_cls_ids))]                                                                                                     
  File "/home/jgibert/KatherLab/HIA/utils/data_utils.py", line 296, in <listcomp>
    weight_per_class = [N/len(dataset.slide_cls_ids[c]) for c in range(len(dataset.slide_cls_ids))]                                                                                                     
ZeroDivisionError: float division by zero
```
After feature extraction. It seems that the splits are not loaded properly but I am not quite sure why.

**Comment by narminGhaffari** [comment]
@Tato14 I am checking the repo, will write you back as soon as I found the problem.
